<html>
<head>
    <base target="_blank">
    <style type="text/css">
        ::-webkit-scrollbar {
            display: none;
        }
    </style>
    <style id="cloudAttachStyle" type="text/css">
        #divNeteaseBigAttach, #divNeteaseBigAttach_bak {
            display: none;
        }
    </style>

</head>
<body tabindex="0" role="listitem">


<div style="background:#f4f4f4; font-family:'微软雅黑'; padding:30px 0; margin:0;">
    <div style="width:900px; margin:0 auto; background:#fafafa;">
        <table cellpadding="0" cellspacing="0" border="0" align="center" width="900px"
               style="font-family: '微软雅黑';font-size: 14px;color: #393737;">
            <tbody>
            <tr bgcolor="#35bdbc" height="100">
                <td width="170" align="center"><img
                        src="http://dev-local.toushibao.com/resource/img/edm/logo_zh_cn.png"></td>
                <td width="550" style="line-height:30px;" align="center">
                    <span style="font-size:20px; color:#fff;">欢迎使用透视宝服务</span><br>
                </td>
                <td width="180"></td>
            </tr>
            </tbody>
        </table>
        <table cellpadding="0" cellspacing="0" border="0" align="center" width="860px"
               style="font-family: '微软雅黑';font-size: 14px;color: #393737;">
            <tbody>
            <tr height="20px"></tr>
            <tr>
                <td width="150" align="center" rowspan="2"><img
                        src="http://dev-local.toushibao.com/resource/img/edm/head_mail.png"></td>
                <td width="750" style="line-height:30px;font-family:'微软雅黑';font-size:16px;">
                    Hi，亲爱的<span style="font-weight: bold;"><?php echo $name;?></span>

                </td>
            </tr>
            <tr style="height: 30px;"></tr>

            <tr>
                <td></td>
                <td style="font-size:14px;font-family:'微软雅黑';">您收到的验证码为:<?php echo $token;?></td>
            </tr>
            <tr height="60">
                <td colspan="2" style="border-bottom: 1px dashed #ddd;"></td>
            </tr>
            <tr height="20px"></tr>
            <tr>
                <td></td>
                <td height="30px">如果您在使用过程中有任何疑问，请随时联系我们：</td>
            </tr>
            <tr height="40px"></tr>

            </tbody>
        </table>
        <table cellpadding="0" cellspacing="0" border="0" align="center" width="860px"
               style="font-family: '微软雅黑';font-size: 14px;color: #393737;">
            <tbody>
            <tr>
                <td width="150"></td>
                <td width="500px" height="30px">微信平台：cloudwise2014</td>
                <td rowspan="3"><img src="http://dev-local.toushibao.com/resource/img/erweima.png"></td>
            </tr>
            <tr>
                <td></td>
                <td height="30px">统一受理热线：010-59426322</td>
            </tr>
            <tr>
                <td></td>
                <td height="30px">
                    统一受理平台：
                    <span><a href="mailto:service@cloudwise.com">service@cloudwise.com</a></span>
                </td>
            </tr>
            <tr height="40"></tr>
            </tbody>
        </table>

    </div>
</div>


<style type="text/css">
    body {
        font-size: 14px;
        font-family: arial, verdana, sans-serif;
        line-height: 1.666;
        padding: 0;
        margin: 0;
        overflow: auto;
        white-space: normal;
        word-wrap: break-word;
        min-height: 100px
    }

    td, input, button, select, body {
        font-family: Helvetica, 'Microsoft Yahei', verdana
    }

    pre {
        white-space: pre-wrap;
        white-space: -moz-pre-wrap;
        white-space: -pre-wrap;
        white-space: -o-pre-wrap;
        word-wrap: break-word;
        width: 95%
    }

    th, td {
        font-family: arial, verdana, sans-serif;
        line-height: 1.666
    }

    img {
        border: 0
    }

    header, footer, section, aside, article, nav, hgroup, figure, figcaption {
        display: block
    }

    blockquote {
        margin-right: 0px
    }
</style>

<style id="ntes_link_color" type="text/css">a, td a {
        color: #064977
    }</style>
</body>
</html>