<?php
use cloudwise\tsb\business\app\web\MessageQueue;
use cloudwise\tsb\datasource\constants\SmartAgentFunctionTypeEnum;
use cloudwise\tsb\datasource\helper\ArrayHelper;

/**
 * Created by PhpStorm.
 * User: napple
 * Date: 17/11/14
 * Time: 下午6:05
 */
class MessageQueueController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $rsTypeMethod = [
            'producer' => SmartAgentFunctionTypeEnum::RABBIT_PRODUCER,
            'consumer' => SmartAgentFunctionTypeEnum::RABBIT_CONSUMER,
        ];
        $this->params['pst'] = ArrayHelper::extractValueFromArray(['type', $this->params, 'producer'], $rsTypeMethod);
    }

    public function getInstanceAndDbnListAction()
    {
        $data = MessageQueue::instance()->getInstanceAndDbnList($this->params);
        $this->rest->success($data);
    }

    public function getServiceTotalTimeTrendAction()
    {
        $data = MessageQueue::instance()->getServiceTotalTimeTrend($this->params);
        $this->rest->success($data);
    }

    public function getRpmAndTimeTrendAction()
    {
        $data = MessageQueue::instance()->getRpmAndTimeTrend($this->params);
        $this->rest->success($data);
    }

    public function getFlowPmTrendAction()
    {
        $data = MessageQueue::instance()->getFlowPmTrend($this->params);
        $this->rest->success($data);
    }

    public function getCallerRateAction()
    {
        $data = MessageQueue::instance()->getCallerRate($this->params);
        $this->rest->success($data);
    }

    public function getConsumerListAction()
    {
        $this->params['pst'] = SmartAgentFunctionTypeEnum::RABBIT_PRODUCER;
        $data = MessageQueue::instance()->getConsumerList($this->params);
        $this->rest->success($data);
    }

    public function getConsumerInstanceListAction()
    {
        $this->params['pst'] = SmartAgentFunctionTypeEnum::RABBIT_CONSUMER;
        $data = MessageQueue::instance()->getConsumerInstanceList($this->params);
        $this->rest->success($data);
    }
}